language: ruby
sudo: false
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
services:
  - redis-server
before_install:
  - gem update --system
  - gem update bundler
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.1.gemfile
