language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
services:
  - redis-server
before_install:
  - gem update --system
  - gem update bundler
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
